refactor icon props components for linter
aptible/cloud-ui pull request #11
Opened 2023-01-06 15:35 UTC by grrowe

- add props interface
- update `any` -> `Props`
    - optional props like `color`
- described component further with `React.FC<Props>`

2023-01-06 16:07 UTC, neurosnap requested changes
`IconFillBase` has `width` and `height` but it is never used in the component.

2023-01-06 16:07 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +export const SmallArrowUp: React.FC<Props> = (props: Props) => {
> In most cases, it makes very little difference which syntax is used, but the React.FC syntax is slightly more verbose without providing clear advantage, so precedence was given to the "normal function" syntax.

https://stackoverflow.com/a/59991281

It seems like we don't need `React.FC<Props>` so I would probably not add it.

2023-01-06 16:07 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +export interface Props extends React.HTMLProps<HTMLDivElement> {
I think this should be `React.SVGProps<SVGSVGElement>`: https://stackoverflow.com/a/60083905

2023-01-06 16:07 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +export const ChevronUp: React.FC<Props> = (props: Props) => {
There are cases where you aren't using `props`.  Please confirm all icons are using them.

2023-01-18 19:09 UTC, grrowe commented on src/ui/shared/icons.tsx
> +export const ChevronUp: React.FC<Props> = (props: Props) => {
confirmed, all icons are using props

2023-01-18 19:09 UTC, grrowe commented on src/ui/shared/icons.tsx
> +export interface Props extends React.HTMLProps<HTMLDivElement> {
You're right, swapped it over.

2023-01-18 19:09 UTC, grrowe commented on src/ui/shared/icons.tsx
> +export const SmallArrowUp: React.FC<Props> = (props: Props) => {
Removed

2023-01-18 19:50 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +      width={width}
Do we ever change the width/height?  If not let's remove the option.

2023-01-18 19:53 UTC, grrowe commented on src/ui/shared/icons.tsx
> +      width={width}
We do not currently, but I am not sure if we will in the future or not. I will remove it now and just add it back in if we need it later.

2023-01-25 15:36 UTC, neurosnap approved these changes

2023-01-25 15:36 UTC, merged