initial icons
aptible/cloud-ui pull request #7
Opened 2022-12-05 16:42 UTC by grrowe

- icon file exporting all icons
- swapped `icn` out for icons
- added magnifying glass to search bar

2022-12-05 16:59 UTC, neurosnap requested changes

2022-12-05 16:59 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +}: {
Let's abstract this into an interface
```ts
interface IconProps {
  color?: string;
  // ...
}
```

2022-12-05 16:59 UTC, neurosnap commented on src/ui/shared/endpoints-overview.tsx
> +                  <PlusCircle color="#ffffff" />{" "}
I think it could be nicer to pre-determine the colors and then ask the end-dev to provide the name.  So instead of hex we would supply "white"

2022-12-07 20:24 UTC, grrowe commented on src/ui/shared/endpoints-overview.tsx
> +                  <PlusCircle color="#ffffff" />{" "}
changed to "white"

2022-12-07 20:24 UTC, grrowe commented on src/ui/shared/icons.tsx
> +}: {
interface IconProps {
  color?: string;
  width?: string;
  height?: string;
  style?: object;
}

2022-12-09 18:33 UTC, neurosnap requested changes
Very close!

2022-12-15 15:51 UTC, grrowe commented on src/ui/shared/app/app-list.tsx
> +            style={{ position: "relative", margin: "5px" }}
Sorry, keep forgetting about this. Updated.

2022-12-15 15:51 UTC, grrowe commented on src/ui/shared/app/app-list.tsx
> +              style={{
There is a top, values are a bit different they use rem instead of px.

2022-12-15 15:52 UTC, grrowe commented on src/ui/shared/icons.tsx
> +    <svg
Created 2 different parent component, one for the stroke color icons and one for the fill color icons.

2022-12-20 16:20 UTC, neurosnap approved these changes
I'd probably delete those comments but it's not a blocker

2022-12-20 16:20 UTC, neurosnap commented on src/ui/shared/icons.tsx
> +// small arrow up
I'm curious, what's the purpose of these comments?

2023-01-05 16:08 UTC, grrowe commented on src/ui/shared/icons.tsx
> +// small arrow up
just to keep track, no real purpose besides readability.

2023-01-05 16:08 UTC, merged